import {
  pgTable,
  bigint,
  text,
  integer,
  real,
  timestamp,
  unique,
  index,
} from "drizzle-orm/pg-core";

// Auth tables (user/session/account/verification/rateLimit) are generated by
// the Better Auth CLI — regenerate with `npm run auth:schema` after changing
// additionalFields in server/auth.ts, never edit auth-schema.ts by hand.
export * from "./auth-schema";

import { user } from "./auth-schema";

/**
 * Favorites + watch-later. One table with a `list_type` discriminator (the
 * app's data layer is parameterized by `kind: "favorite" | "watchlist"`).
 * Card metadata (title/poster/date/rating) is denormalized onto each row so
 * the saved pages render without re-hitting TMDB.
 */
export const savedItems = pgTable(
  "saved_items",
  {
    id: bigint("id", { mode: "number" })
      .primaryKey()
      .generatedAlwaysAsIdentity(),
    // Better Auth ids are text, not uuid.
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    listType: text("list_type").notNull(), // 'favorite' | 'watchlist'
    mediaType: text("media_type").notNull(), // 'movie' | 'tv'
    mediaId: integer("media_id").notNull(), // TMDB id
    title: text("title"),
    posterPath: text("poster_path"),
    releaseDate: text("release_date"), // raw date or 4-char year — both render
    voteAverage: real("vote_average"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    // media_type MUST be in the key: movie 123 and tv 123 are distinct titles.
    unique("saved_items_user_list_media_uq").on(
      t.userId,
      t.listType,
      t.mediaType,
      t.mediaId,
    ),
    // Serves the list fetch: WHERE user_id AND list_type ORDER BY created_at desc.
    index("saved_items_user_list_created_idx").on(
      t.userId,
      t.listType,
      t.createdAt,
    ),
  ],
);

export type SavedItem = typeof savedItems.$inferSelect;
